<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2vxHgn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2vxHgn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2vxHgn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2vxHgn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX2vxHgn\App_KernelDevDebugContainer([
    'container.build_hash' => 'X2vxHgn',
    'container.build_id' => 'c9f7d82e',
    'container.build_time' => 1637523907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2vxHgn');
